full_name: "Coleman Word"
github_username: "gofunct"
app_name: "mygolangproject"
project_short_description: "A Golang project."
docker_hub_username: "colemanword"
docker_image: "golang:1.11"
docker_build_image: "golang:1.11"
docker_build_image_version: ["1.11" "1.10.3" "1.9.7"]
go_mod_or_dep: ["dep" "mod"]
use_docker: "y"
use_git: "y"
use_logrus_logging: "y"
use_viper_config: "y"
use_cobra_cmd: "y"
